# Build docker buildx for AMD64, Arm64 and ArmV7
name: CI

# Only build on pushes to master and to ghcr:master
on:
  push:
    branches:
      - "trunk"
    paths-ignore:
      - '**/**.md'
env:
  REGISTRY_GHCR: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@e5622373a38e60fb6d795a4421e56882f2d7a681
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: type=raw,value=latest

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY_GHCR }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ env.REGISTRY_GHCR }}/${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=user/app:latest
          cache-to: type=inline